version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: tree-kill
    versions:
    - 1.2.2
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
